# .circleci/config.yml
version: 2.1

orbs:
  node: circleci/node@5.1.0
  codecov: codecov/codecov@3.2.5

jobs:
  test:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          override-ci-command: npm ci
      
      - run:
          name: Run Linter
          command: npm run lint
      
      - run:
          name: Type Check
          command: npm run typecheck
      
      - run:
          name: Run Tests
          command: npm test

      - run:
          name: Build Project
          command: npm run build
          
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  coverage:
    docker:
      - image: cimg/node:18.16
    steps:
      - attach_workspace:
          at: ~/project
      
      - run:
          name: Run Tests with Coverage
          command: npm run test:coverage
      
      - codecov/upload:
          file: './coverage/lcov.info'

workflows:
  version: 2
  build-test:
    jobs:
      - test
      - coverage:
          requires:
            - test